### ISSUE TITLE
includeParents use negative values as "except"

### ISSUE THREAD

**Issue by fkammer** [armed/gulp-flatten#10]
I'm working on an angular project and my application is split into different modules like `core` and `manage`. Some modules (in this example the `manage` module) have additional submodules (here `users`). All modules and submodules have directories for their controllers and partials.

My folder structure looks like this:
````
└── src
    ├── core
    |   ├── controllers
    |   └── partials
    └── manage
        ├── controllers
        ├── partials
        └── users
            ├── controllers
            └── partials
````
All files from `src` are compiled or copied to the folder `public` that has a subfolder `partials`.
Right now my task looks like this:
````coffeescript
# coffeescript
gulp.task 'html', ->
  gulp.src './src/**/*.jade', {base: './src'}
    .pipe jade()
    .pipe gulp.dest './public/partials'
````
The partials from `src/core/partials/` are stored in `public/partials/core/partials/`; partials from `src/manage/users/partials/` in `public/partials/manage/users/partials/`. The additional `partials` at the end bothers me a lot.

As the transition of the first part (`src/` to `public/partials/`) is already handled by `gulp.src` and `gulp.dest`, I'm looking for a possibility to eliminate the last part of the path. As I don't know how many parents it has in total (`core/partials/` vs. `manage/users/partials/`) I can't achieve this with the current `includeParents` option.

I suggest to use negative values as except conditions. So that `includeParents: [-1, -1]` would transform `part1/part2/part3/part4/` to `part2/part3/`.

What do you think? I would be happy to commit a pull request.

**Comment by armed** [comment]
Hi, @fkammer 

First of all, thank you for great explanation. I like your idea, but I suggest to create new option (e.g. `excludeParents`) instead of overusing existing `includeParents`. 

`excludeParents` can be used by analogy to `inclideParents`:

* `excludeParents: 1` to exclude top level folders
* `excludeParents: -1` or `excludeParents: [0, 1]` to exclude bottom level folders

What do you think?

**Comment by fkammer** [comment]
Hey @armed,

thanks for your quick reply. An `excludeParents` option sounds good too. But it's hard to predict what exactly happens when you combine both.

I had PHPs `substr` method in mind (http://php.net/manual/en/function.substr.php). What do you think about a new option `subPath` with the same syntax like `substr`? It would keep backwards compatibility but is way more customizable.

**Comment by armed** [comment]
@fkammer,

I like `subPath` idea and accept your PR.
