### ISSUE TITLE
Add support for filesystem depth

### ISSUE THREAD

**Issue by georgeh** [armed/gulp-flatten#5]
I'd like to be able to be able to choose how deep to flatten the directory tree with an option. I'm calling the option "includeParents" since I think it's more descriptive than "depth"

To use the example from the README file, this is what the new option would look like:

```js
var flatten = require('gulp-flatten');

gulp.src(['bower_components/**/*.min.js', 'bower_components/**/*.css'])
  .pipe(flatten({ includeParents: 1} ))
  .pipe(gulp.dest('build/'));
```

And it would create this structure:

```
├── angular
│   ├── angular-csp.css
│   └── angular.min.js
├── angular-route
│   └── angular-route.min.js
├── angular-sanitize
│   └── angular-sanitize.min.js
└── bootstrap
    ├── bootstrap-theme.css
    ├── bootstrap-theme.min.css
    ├── bootstrap.css
    ├── bootstrap.min.css
    └── bootstrap.min.js
```

This would be helpful for me to keep CSS/JS/fonts all together for Bower components. Is this something you would be interested in adding/accepting PRs for?

**Comment by armed** [comment]
Hi,

Nice idea, I like it. PR welcome.

**Comment by armed** [comment]
I would be great if you add tests for new feature too.

**Comment by armed** [comment]
Thanks for PR, closing. Just published updated version to npmjs.

**Comment by PLEEROCK** [comment]
would be great to have this option that will work reverse way

**Comment by armed** [comment]
@PLEEROCK can you explain with example?
