### ISSUE TITLE
FileSystem Depth: In Reverse

### ISSUE THREAD

**Issue by AleskiWeb** [armed/gulp-flatten#8]
First off, thanks for taking the time to make such a great tool, love it. I like the implementation of the `{ includeParents: 1 }` however I believe this is taking the highest level.

I was wondering what I would do to extract the next parent up, as apposed to starting at the base path. For example:

    path/to/stuff/file.js

When using `.pipe(flatten({ includeParents: 1 }))` on the above path, seems to bring back the first level from the top (aka `path`).

    build/lib/path/file.js

How would I get the path for `stuff` using gulp-flatten?

    build/lib/stuff/file.js

I hope you understand, hard to really explain what I mean but I did the best I could.

**Comment by armed** [comment]
Hi, I got your point. 

I'm thinking to handle negative numbers in `includeParents` for this purpose. Don't know whether is intuitive or I should make another option. What do you think, @AleskiWeb?

**Comment by AleskiWeb** [comment]
Hi @armed and thanks for the quick reply. Yeah I think that sounds intuitive enough, only other way would be to create a new method called `options.IncludeParentsReverse` but either way sounds about as intuitive. I just think if it was a different option then you could, for example:

    really/complex/build/system/file.js

if you wanted to get the end result of 

    really/system/file.js

Then the negative numbers way wouldn't really allow for it. If it was a different option you could use:

    .pipe(flatten({ includeParents: 1, includeParentsReverse: 1 }))

Not sure if that is a fair scenario but just something to consider? Either way would be fine for my particular instance.

**Comment by armed** [comment]
@AleskiWeb, just published 0.2.0 to npm. Both top and bottom parents now supported. See readme.
